name: gds

on:
  push:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install sv2v
        run: |
          wget -O - https://raw.githubusercontent.com/sifferman/hdl-tool-installer/main/install | bash -s -- . --zachjs-sv2v
          echo "$GITHUB_WORKSPACE/zachjs-sv2v" >> $GITHUB_PATH

      - name: Run sv2v
        run: |
          cd src/sifferman_temporal_encoder_decoder
          sv2v rtl/temporal_encoder_helper.sv rtl/temporal_encoder.sv rtl/temporal_decoder.sv -DSYNTHESIS -w rtl.sv2v.v
          git add -f rtl.sv2v.v

      - name: Build GDS
        uses: TinyTapeout/tt-gds-action@ttsky25b
        with:
          pdk: sky130A

  precheck:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: Run Tiny Tapeout Precheck
        uses: TinyTapeout/tt-gds-action/precheck@ttsky25b

  gl_test:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install sv2v
        run: |
          wget -O - https://raw.githubusercontent.com/sifferman/hdl-tool-installer/main/install | bash -s -- . --zachjs-sv2v
          echo "$GITHUB_WORKSPACE/zachjs-sv2v" >> $GITHUB_PATH

      - name: Run sv2v
        run: |
          cd src/sifferman_temporal_encoder_decoder
          sv2v rtl/temporal_encoder_helper.sv rtl/temporal_encoder.sv rtl/temporal_decoder.sv -DSYNTHESIS -w rtl.sv2v.v

      - name: GL test
        uses: TinyTapeout/tt-gds-action/gl_test@ttsky25b

  viewer:
    needs: gds
    runs-on: ubuntu-24.04
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - uses: TinyTapeout/tt-gds-action/viewer@ttsky25b
